### ISSUE TITLE
Pip does not supply binaries for windows / specpart and fortran installation issues

### ISSUE THREAD

**Issue by RubendeBruin** [wavespectra/wavespectra#114]
According to the documentation pip should supply binaries for wave-spectra. However when installing wavespectra via pip it seems that the package is still build for source locally, resulting in failures when a fortran compiler is not available.

(waves) C:\python\venvs\waves\Scripts>pip install wavespectra
Collecting wavespectra
  Downloading wavespectra-3.18.0.tar.gz (69 kB)

  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
.......
Building wheels for collected packages: wavespectra
  Building wheel for wavespectra (pyproject.toml) ... error

**Comment by RubendeBruin** [comment]
cross-link: https://github.com/wavespectra/wavespectra/discussions/113

**Comment by RubendeBruin** [comment]
Using: https://github.com/pypa/cibuildwheel/tree/main
it could be as easy as 
https://github.com/pypa/cibuildwheel/blob/main/examples/github-deploy.yml

**Comment by rafa-guedes** [comment]
Related to https://github.com/wavespectra/wavespectra/issues/96

**Comment by rafa-guedes** [comment]
Implemented in v4, wavespectra now installs directly from pip on Windows (from version 4.0.2 onwards).
