### ISSUE TITLE
UserWarning: Cannot import accessors at the main module level

### ISSUE THREAD

**Issue by LWCAO** [wavespectra/wavespectra#119]
When I  run below  python code,  encountered  with some errors: 

from wavespectra import read_ww3
dset = read_ww3( "ww3file.nc")
dset.spec

error messages:

C:\Anaconda\lib\site-packages\wavespectra\__init__.py:13: UserWarning: Cannot import accessors at the main module level
  warnings.warn("Cannot import accessors at the main module level")
Cannot import reading function read_dataset because:
cannot import name 'deprecated' from 'typing_extensions' (C:\Anaconda\lib\site-packages\typing_extensions.py)
Cannot import reading function read_era5 because:
cannot import name 'deprecated' from 'typing_extensions' (C:\Anaconda\lib\site-packages\typing_extensions.py)
Cannot import reading function read_funwave because:
cannot import name 'SpecArray' from partially initialized module 'wavespectra' (most likely due to a circular import) (C:\Anaconda\lib\site-packages\wavespectra\__init__.py)
Cannot import reading function read_ncswan because:
cannot import name 'deprecated' from 'typing_extensions' (C:\Anaconda\lib\site-packages\typing_extensions.py)
Cannot import reading function read_ndbc because:
cannot import name 'deprecated' from 'typing_extensions' (C:\Anaconda\lib\site-packages\typing_extensions.py)
Cannot import reading function read_ndbc_ascii because:
cannot import name 'deprecated' from 'typing_extensions' (C:\Anaconda\lib\site-packages\typing_extensions.py)
Cannot import reading function read_netcdf because:
cannot import name 'deprecated' from 'typing_extensions' (C:\Anaconda\lib\site-packages\typing_extensions.py)
Cannot import reading function read_octopus because:
cannot import name 'deprecated' from 'typing_extensions' (C:\Anaconda\lib\site-packages\typing_extensions.py)
Cannot import reading function read_spotter because:
cannot import name 'deprecated' from 'typing_extensions' (C:\Anaconda\lib\site-packages\typing_extensions.py)
Cannot import reading function read_swan because:
cannot import name 'deprecated' from 'typing_extensions' (C:\Anaconda\lib\site-packages\typing_extensions.py)
Cannot import reading function read_triaxys because:
cannot import name 'deprecated' from 'typing_extensions' (C:\Anaconda\lib\site-packages\typing_extensions.py)
Cannot import reading function read_wavespectra because:
cannot import name 'deprecated' from 'typing_extensions' (C:\Anaconda\lib\site-packages\typing_extensions.py)
Cannot import reading function read_ww3 because:
cannot import name 'deprecated' from 'typing_extensions' (C:\Anaconda\lib\site-packages\typing_extensions.py)
Cannot import reading function read_wwm because:
cannot import name 'deprecated' from 'typing_extensions' (C:\Anaconda\lib\site-packages\typing_extensions.py)
Traceback (most recent call last):
  File "d:/wave_spectra_post/exmaple.py", line 1, in <module>
    from wavespectra import read_ww3
ImportError: cannot import name 'read_ww3' from 'wavespectra' (C:\Anaconda\lib\site-packages\wavespectra\__init__.py)

**Comment by rafa-guedes** [comment]
Hi @LWCAO it looks this may be related to https://github.com/wavespectra/wavespectra/issues/118.

**Comment by LWCAO** [comment]
thanks a lot. it solved by upgrade some package!

**Comment by rafa-guedes** [comment]
Sounds good @LWCAO , before we close this one then could you please tell us which package did you need to upgrade in case someone else has the same issues? Thanks!
