### ISSUE TITLE
Issue with wavespectra.SpecArray.split

### ISSUE THREAD

**Issue by Taddei-S** [wavespectra/wavespectra#124]
The comments in wavespectra.SpecArray.split say: Split spectra over freq AND/OR dir dims, but the slicing in the dir dimension overrides the slicing in the freq dimension. Is this the desired behavior?

Suggestion:
It might be helpful if we could choose between options like:

dsets = dset.sel(dir=slice(dmin,dmax),freq=slice(fmin,fmax))

i.e. slice, or

dsetw = dset.where(((ds.dir >= dmin) & (ds.dir <= dmax)) & ((ds.freq >= fmin) & (ds.freq <= fmax)), other=0)

i.e., with zeros elsewhere. For example, for plotting reasons.

**Comment by rafa-guedes** [comment]
@Taddei-S you are right, there was a bug with the direction slicing. I have fixed this in https://github.com/wavespectra/wavespectra/commit/ece404142bbd1db7ae1f9de8a690a8f34a708f91, it will be included in the next release.

This new release will also have a new partitioning api with the addition of a few new methods and one of them is defined as `bbox` - which will do what you have suggested based on the masking. The output will be a new dataset with a new `part` dim (similar to the watershed output) with two partitions, where one has the spectra values within the bbox(es) defined, and zeros elsewhere, and the other has the spectra outside the bboxes.

**Comment by rafa-guedes** [comment]
Will be fixed with https://github.com/wavespectra/wavespectra/pull/106

**Comment by rafa-guedes** [comment]
Done in v4.0.0
