### ISSUE TITLE
pip install wavespectra install error for wavespectra=4.0.0

### ISSUE THREAD

**Issue by nikorpt** [wavespectra/wavespectra#128]
Hi all, it seems that i have some difficulties to install wavespectra=4.0.0 on python=3.10 and Linux.

Thanks for your help ;) !

Collecting wavespectra
  Using cached wavespectra-4.0.0.tar.gz (99 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting click (from wavespectra)
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting dask (from wavespectra)
  Using cached dask-2024.5.2-py3-none-any.whl.metadata (3.8 kB)
Collecting matplotlib (from wavespectra)
  Using cached matplotlib-3.9.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
Collecting python-dateutil (from wavespectra)
  Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting pyyaml (from wavespectra)
  Using cached PyYAML-6.0.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.1 kB)
Collecting sortedcontainers (from wavespectra)
  Using cached sortedcontainers-2.4.0-py2.py3-none-any.whl.metadata (10 kB)
Collecting scipy (from wavespectra)
  Using cached scipy-1.13.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
Collecting xarray (from wavespectra)
  Using cached xarray-2024.6.0-py3-none-any.whl.metadata (11 kB)
Collecting cloudpickle>=1.5.0 (from dask->wavespectra)
  Using cached cloudpickle-3.0.0-py3-none-any.whl.metadata (7.0 kB)
Collecting fsspec>=2021.09.0 (from dask->wavespectra)
  Using cached fsspec-2024.6.0-py3-none-any.whl.metadata (11 kB)
Collecting packaging>=20.0 (from dask->wavespectra)
  Using cached packaging-24.1-py3-none-any.whl.metadata (3.2 kB)
Collecting partd>=1.2.0 (from dask->wavespectra)
  Using cached partd-1.4.2-py3-none-any.whl.metadata (4.6 kB)
Collecting toolz>=0.10.0 (from dask->wavespectra)
  Using cached toolz-0.12.1-py3-none-any.whl.metadata (5.1 kB)
Collecting importlib-metadata>=4.13.0 (from dask->wavespectra)
  Using cached importlib_metadata-7.1.0-py3-none-any.whl.metadata (4.7 kB)
Collecting contourpy>=1.0.1 (from matplotlib->wavespectra)
  Using cached contourpy-1.2.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.8 kB)
Collecting cycler>=0.10 (from matplotlib->wavespectra)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib->wavespectra)
  Using cached fonttools-4.53.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (162 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib->wavespectra)
  Using cached kiwisolver-1.4.5-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl.metadata (6.4 kB)
Collecting numpy>=1.23 (from matplotlib->wavespectra)
  Using cached numpy-1.26.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
Collecting pillow>=8 (from matplotlib->wavespectra)
  Using cached pillow-10.3.0-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (9.2 kB)
Collecting pyparsing>=2.3.1 (from matplotlib->wavespectra)
  Using cached pyparsing-3.1.2-py3-none-any.whl.metadata (5.1 kB)
Collecting six>=1.5 (from python-dateutil->wavespectra)
  Using cached six-1.16.0-py2.py3-none-any.whl.metadata (1.8 kB)
Collecting pandas>=2.0 (from xarray->wavespectra)
  Using cached pandas-2.2.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (19 kB)
Collecting zipp>=0.5 (from importlib-metadata>=4.13.0->dask->wavespectra)
  Using cached zipp-3.19.2-py3-none-any.whl.metadata (3.6 kB)
Collecting pytz>=2020.1 (from pandas>=2.0->xarray->wavespectra)
  Using cached pytz-2024.1-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas>=2.0->xarray->wavespectra)
  Using cached tzdata-2024.1-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting locket (from partd>=1.2.0->dask->wavespectra)
  Using cached locket-1.0.0-py2.py3-none-any.whl.metadata (2.8 kB)
Using cached click-8.1.7-py3-none-any.whl (97 kB)
Using cached dask-2024.5.2-py3-none-any.whl (1.2 MB)
Using cached PyYAML-6.0.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (705 kB)
Using cached matplotlib-3.9.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (8.3 MB)
Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
Using cached scipy-1.13.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (38.6 MB)
Using cached sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Using cached xarray-2024.6.0-py3-none-any.whl (1.2 MB)
Using cached cloudpickle-3.0.0-py3-none-any.whl (20 kB)
Using cached contourpy-1.2.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (305 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Using cached fonttools-4.53.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.6 MB)
Using cached fsspec-2024.6.0-py3-none-any.whl (176 kB)
Using cached importlib_metadata-7.1.0-py3-none-any.whl (24 kB)
Using cached kiwisolver-1.4.5-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.6 MB)
Using cached numpy-1.26.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.2 MB)
Using cached packaging-24.1-py3-none-any.whl (53 kB)
Using cached pandas-2.2.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.0 MB)
Using cached partd-1.4.2-py3-none-any.whl (18 kB)
Using cached pillow-10.3.0-cp310-cp310-manylinux_2_28_x86_64.whl (4.5 MB)
Using cached pyparsing-3.1.2-py3-none-any.whl (103 kB)
Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Using cached toolz-0.12.1-py3-none-any.whl (56 kB)
Using cached pytz-2024.1-py2.py3-none-any.whl (505 kB)
Using cached tzdata-2024.1-py2.py3-none-any.whl (345 kB)
Using cached zipp-3.19.2-py3-none-any.whl (9.0 kB)
Using cached locket-1.0.0-py2.py3-none-any.whl (4.4 kB)
Building wheels for collected packages: wavespectra
  Building wheel for wavespectra (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for wavespectra (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [88 lines of output]
      No `packages` or `py_modules` configuration, performing automatic discovery.
      `flat-layout` detected -- analysing .
      discovered packages -- ['wavespectra', 'wavespectra.partition', 'wavespectra.output', 'wavespectra.construct', 'wavespectra.core', 'wavespectra.input', 'wavespectra.partition.specpart']
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-310
      creating build/lib.linux-x86_64-cpython-310/wavespectra
      copying wavespectra/specdataset.py -> build/lib.linux-x86_64-cpython-310/wavespectra
      copying wavespectra/cli.py -> build/lib.linux-x86_64-cpython-310/wavespectra
      copying wavespectra/plot.py -> build/lib.linux-x86_64-cpython-310/wavespectra
      copying wavespectra/specarray.py -> build/lib.linux-x86_64-cpython-310/wavespectra
      copying wavespectra/__init__.py -> build/lib.linux-x86_64-cpython-310/wavespectra
      creating build/lib.linux-x86_64-cpython-310/wavespectra/partition
      copying wavespectra/partition/tracking.py -> build/lib.linux-x86_64-cpython-310/wavespectra/partition
      copying wavespectra/partition/partition.py -> build/lib.linux-x86_64-cpython-310/wavespectra/partition
      copying wavespectra/partition/hanson_and_phillips_2001.py -> build/lib.linux-x86_64-cpython-310/wavespectra/partition
      copying wavespectra/partition/__init__.py -> build/lib.linux-x86_64-cpython-310/wavespectra/partition
      creating build/lib.linux-x86_64-cpython-310/wavespectra/output
      copying wavespectra/output/json.py -> build/lib.linux-x86_64-cpython-310/wavespectra/output
      copying wavespectra/output/orcaflex.py -> build/lib.linux-x86_64-cpython-310/wavespectra/output
      copying wavespectra/output/netcdf.py -> build/lib.linux-x86_64-cpython-310/wavespectra/output
      copying wavespectra/output/ww3.py -> build/lib.linux-x86_64-cpython-310/wavespectra/output
      copying wavespectra/output/funwave.py -> build/lib.linux-x86_64-cpython-310/wavespectra/output
      copying wavespectra/output/swan.py -> build/lib.linux-x86_64-cpython-310/wavespectra/output
      copying wavespectra/output/__init__.py -> build/lib.linux-x86_64-cpython-310/wavespectra/output
      copying wavespectra/output/octopus.py -> build/lib.linux-x86_64-cpython-310/wavespectra/output
      creating build/lib.linux-x86_64-cpython-310/wavespectra/construct
      copying wavespectra/construct/direction.py -> build/lib.linux-x86_64-cpython-310/wavespectra/construct
      copying wavespectra/construct/frequency.py -> build/lib.linux-x86_64-cpython-310/wavespectra/construct
      copying wavespectra/construct/__init__.py -> build/lib.linux-x86_64-cpython-310/wavespectra/construct
      creating build/lib.linux-x86_64-cpython-310/wavespectra/core
      copying wavespectra/core/fitting.py -> build/lib.linux-x86_64-cpython-310/wavespectra/core
      copying wavespectra/core/xrstats.py -> build/lib.linux-x86_64-cpython-310/wavespectra/core
      copying wavespectra/core/select.py -> build/lib.linux-x86_64-cpython-310/wavespectra/core
      copying wavespectra/core/utils.py -> build/lib.linux-x86_64-cpython-310/wavespectra/core
      copying wavespectra/core/npstats.py -> build/lib.linux-x86_64-cpython-310/wavespectra/core
      copying wavespectra/core/attributes.py -> build/lib.linux-x86_64-cpython-310/wavespectra/core
      copying wavespectra/core/swan.py -> build/lib.linux-x86_64-cpython-310/wavespectra/core
      copying wavespectra/core/__init__.py -> build/lib.linux-x86_64-cpython-310/wavespectra/core
      creating build/lib.linux-x86_64-cpython-310/wavespectra/input
      copying wavespectra/input/ww3_station.py -> build/lib.linux-x86_64-cpython-310/wavespectra/input
      copying wavespectra/input/ndbc_ascii.py -> build/lib.linux-x86_64-cpython-310/wavespectra/input
      copying wavespectra/input/spotter.py -> build/lib.linux-x86_64-cpython-310/wavespectra/input
      copying wavespectra/input/json.py -> build/lib.linux-x86_64-cpython-310/wavespectra/input
      copying wavespectra/input/era5.py -> build/lib.linux-x86_64-cpython-310/wavespectra/input
      copying wavespectra/input/dataset.py -> build/lib.linux-x86_64-cpython-310/wavespectra/input
      copying wavespectra/input/netcdf.py -> build/lib.linux-x86_64-cpython-310/wavespectra/input
      copying wavespectra/input/ww3.py -> build/lib.linux-x86_64-cpython-310/wavespectra/input
      copying wavespectra/input/xwaves.py -> build/lib.linux-x86_64-cpython-310/wavespectra/input
      copying wavespectra/input/wwm.py -> build/lib.linux-x86_64-cpython-310/wavespectra/input
      copying wavespectra/input/wavespectra.py -> build/lib.linux-x86_64-cpython-310/wavespectra/input
      copying wavespectra/input/triaxys.py -> build/lib.linux-x86_64-cpython-310/wavespectra/input
      copying wavespectra/input/ncswan.py -> build/lib.linux-x86_64-cpython-310/wavespectra/input
      copying wavespectra/input/funwave.py -> build/lib.linux-x86_64-cpython-310/wavespectra/input
      copying wavespectra/input/ndbc.py -> build/lib.linux-x86_64-cpython-310/wavespectra/input
      copying wavespectra/input/swan.py -> build/lib.linux-x86_64-cpython-310/wavespectra/input
      copying wavespectra/input/obscape.py -> build/lib.linux-x86_64-cpython-310/wavespectra/input
      copying wavespectra/input/__init__.py -> build/lib.linux-x86_64-cpython-310/wavespectra/input
      copying wavespectra/input/octopus.py -> build/lib.linux-x86_64-cpython-310/wavespectra/input
      running egg_info
      writing wavespectra.egg-info/PKG-INFO
      writing dependency_links to wavespectra.egg-info/dependency_links.txt
      writing entry points to wavespectra.egg-info/entry_points.txt
      writing requirements to wavespectra.egg-info/requires.txt
      writing top-level names to wavespectra.egg-info/top_level.txt
      reading manifest file 'wavespectra.egg-info/SOURCES.txt'
      adding license file 'LICENSE.txt'
      adding license file 'AUTHORS.rst'
      writing manifest file 'wavespectra.egg-info/SOURCES.txt'
      copying wavespectra/output/ww3.yml -> build/lib.linux-x86_64-cpython-310/wavespectra/output
      copying wavespectra/core/attributes.yml -> build/lib.linux-x86_64-cpython-310/wavespectra/core
      creating build/lib.linux-x86_64-cpython-310/wavespectra/partition/specpart
      copying wavespectra/partition/specpart/specpartc.c -> build/lib.linux-x86_64-cpython-310/wavespectra/partition/specpart
      copying wavespectra/partition/specpart/specpartc_wrap.c -> build/lib.linux-x86_64-cpython-310/wavespectra/partition/specpart
      running build_ext
      building 'wavespectra.partition.specpartc' extension
      creating build/temp.linux-x86_64-cpython-310
      creating build/temp.linux-x86_64-cpython-310/wavespectra
      creating build/temp.linux-x86_64-cpython-310/wavespectra/partition
      creating build/temp.linux-x86_64-cpython-310/wavespectra/partition/specpart
      gcc -pthread -B /root/miniconda3/envs/test2/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /root/miniconda3/envs/test2/include -fPIC -O2 -isystem /root/miniconda3/envs/test2/include -fPIC -I/tmp/pip-build-env-it19102v/overlay/lib/python3.10/site-packages/numpy/core/include -I/root/miniconda3/envs/test2/include/python3.10 -c wavespectra/partition/specpart/specpartc.c -o build/temp.linux-x86_64-cpython-310/wavespectra/partition/specpart/specpartc.o
      wavespectra/partition/specpart/specpartc.c:4:10: fatal error: specpartc.h: Aucun fichier ou dossier de ce type
          4 | #include "specpartc.h"
            |          ^~~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for wavespectra

**Comment by rafa-guedes** [comment]
@nikorpt thank you for reporting this issue. The path for the header file was incorrectly specified and it was not packaged with the distribution. This has been fixed in `v4.0.1`. Please try to install that latest version.

**Comment by nikorpt** [comment]
Thanks @rafa-guedes  ! I really like wavespectra ;)

**Comment by nikorpt** [comment]
Thanks !
