### ISSUE TITLE
Negative NDBC directional energy spectrum

### ISSUE THREAD

**Issue by lubyant** [wavespectra/wavespectra#136]
According to NOAA doc, directional spectrum could be negative due to trigonometric function. This could be an issue (for example, take log value). Here is the description from the NOAA. 
![image](https://github.com/user-attachments/assets/1eabe40f-508f-4e5d-82f4-ed08e69903c0)
Do you think about add the optional feature to adjust those negative spectrum? The solution is fairly straightforward, introduced by this paper: _Use of advanced directional wave spectra analysis methods_
![image](https://github.com/user-attachments/assets/3ff95774-24a1-47e7-9037-11a4faf9bed6)

**Comment by rafa-guedes** [comment]
@lubyant thanks for this suggestion. Do you see those negative values often in the ndbc spectra? Would you be willing to have a go and send a pull request at this please? You can find the code that reads ndbc spectra [here](https://github.com/wavespectra/wavespectra/blob/master/wavespectra/input/ndbc.py). Thanks!

**Comment by lubyant** [comment]
Yes, they do. Triangometric should cause periodic positive-negative switch all the time. 
You can assign me this issue, and I would submit pr in the next few day.

**Comment by RubendeBruin** [comment]
FYI,
I think the same is implemented here:

https://github.com/wavespectra/wavespectra/blob/a25b5ea1fefa6b29525a1a9195c09847f935563d/wavespectra/input/awac.py#L400

**Comment by daniel-caichac-DHI** [comment]
Hi @lubyant , have you had a chance to work on this? 
I just want to confirm that almost in every 2D spectra I reconstruct from NDBC Buoys, I get negative values, and not negligible at all.

In some timestep my max energy density bin (in etfh) is eg +12 m2/deg/hz, and in the same timestep the minimum energy bin (in etfh) has -6 m2/deg/hz. 

This is very common when reconstructing NDBC 2D spectra (no issues with the 1D spectra).

**Comment by lubyant** [comment]
@daniel-caichac-DHI yeah, I can echo his point that almost every case of reconstruction could lead to negative spectrum energy due to trigonometry.
I will submit pr to solve this issue. The solution is pretty straghtforward and elegant in math - just adjust the coeffecient such that removes all negatives while integrals still stay the same. Here are some experiments:
Before weight:
![image](https://github.com/user-attachments/assets/1d3a386c-122f-42a6-8b34-31c2fbc59167)
After weight:
![image](https://github.com/user-attachments/assets/68c45555-cf11-4805-ad01-585bdb94978f)
You will observe the negative values disappear without changing the overall pattern of spectrum.
