### ISSUE TITLE
Can wave direction spectra be computed by this code from buoy motion data

### ISSUE THREAD

**Issue by yangleir** [wavespectra/wavespectra#138]
Hello,

I am currently exploring the capabilities of your codes and I have a question regarding the computation of wave direction spectra. From the initial review of the documentation, it appears that the library primarily supports reading pre-computed directional spectra from standard products. Is there functionality within wavespectra to compute directional spectra directly from three-dimensional motion data observed by wave buoys?

If such functionality does not exist, could you provide some guidance on how one might go about computing this? Are there any open-source codes available that you could recommend for this purpose?

Thank you for your assistance.

Best regards,
Lei

**Comment by rafa-guedes** [comment]
Hi @yangleir,

computing spectra from buoy or pressure sensor data is out of the wavespectra scope. There is a nice package written by @davemetocean to do that called [diwasp](https://github.com/metocean/diwasp). It is a Matlab package, not python but I think I have seen some attempts to translate it to python so you may be able to find something.
