### ISSUE TITLE
read_datawell missing from conda package

### ISSUE THREAD

**Issue by WouterAntheunisse** [wavespectra/wavespectra#139]
Hi there, 

I've installed wavespectra using `conda install conda-forge::wavespectra` (python 3.11 on windows) and it appears that the datawell.py is missing from the input module after installation. Therefore I can't use read_datawell.  

Also, not sure if this is a related issue, but the win-64 variant of the conda package is still at v4.0.3

Regards, 
Wouter

**Comment by rafa-guedes** [comment]
@WouterAntheunisse thanks for reporting this. The new code is only available from v4.1.0. It sounds like the conda package isn't up to date for some reason. I will try and have a look soon, in the meanwhile perhaps you could try to install v4.1.0 using pip instead.

**Comment by rafa-guedes** [comment]
This is fixed in v4.1.1, [conda-forge](https://anaconda.org/conda-forge/wavespectra) is now up to date for the Windows installer with the latest wavespectra version that includes the new Datawell reader
