### ISSUE TITLE
compiling specpart

### ISSUE THREAD

**Issue by RubendeBruin** [wavespectra/wavespectra#31]
Hi @rafa-guedes 
tried to install wavespectra via pip but got some errors about missing a fortran compiler. I'm on a corporate windows machine so that makes sense.

I think adding conda-forge as a additional distribution channel (besides pip) can solve this problem for people on machines like mine. Willing to set this up for you if you want.

**Comment by rafa-guedes** [comment]
Hi @RubendeBruin yes the fortran module is an issue on Windows machines. The workaround we currently provide is an alternative [pure-python](https://github.com/wavespectra/wavespectra/tree/pure-python) branch (with the fortran module replaced by a python one) - which we have been attempting to keep up-to-date with each latest release (the code is a lot slower though if you are dealing with very large datasets). But yes if you are willing to set up the conda-forge distribution that would be certainly welcome, we appreciate any contributions to the library!

**Comment by RubendeBruin** [comment]
great!
The conda-forge recipe merge request is prepared. Just your ok and then I can remove the WIP

https://github.com/conda-forge/staged-recipes/pull/14281#issuecomment-801163281

Compiling seems to work as well [details](https://github.com/conda-forge/staged-recipes/pull/14281/checks?check_run_id=2133253069)

**Comment by rafa-guedes** [comment]
Sounds great! Would you mind writing a short instruction in the [Install section](https://github.com/wavespectra/wavespectra/blob/master/docs/install.rst#from-sources) of the docs please, probably just before `From sources` subsection?

I am not too familiar with conda but I'm happy to be listed as a maintainer of the recipe alongside you. What is the workflow when we release new versions of the library?

**Comment by RubendeBruin** [comment]
hi @rafa-guedes 

can you give your ok in the following issue: https://github.com/conda-forge/staged-recipes/pull/14281

The workflow for new releases is pretty straight forward. The conda-forge pipeline fetches the package from pypi, compiles it and makes it available to be installed via conda.
The conda-forge robot will detect if a new version is published in pypi. It will then automatically prepare a merge-request for the repository that holds the pipeline recipe. We both will receive an email about that because we're both maintainers. Then it's simply pressing the "merge" button.

I'll create a MR for the installation instructions.

**Comment by RubendeBruin** [comment]
@rafa-guedes 

The packages:

    - attrdict
    - decorator
    - importlib-metadata

seem to be required to run the tests, but they are not in the installation requirements. Should they be added to the installation requirements?

**Comment by rafa-guedes** [comment]
`attrdict` has been removed from the library in the latest pull request which is about to be merged so that won't be required anymore. The other two are not imported directly in wavespectra, I'm not sure where they are required?

**Comment by RubendeBruin** [comment]
solved - conda-forge does not run the tests so indeed not relevant here.
