### ISSUE TITLE
bug in spreading function

### ISSUE THREAD

**Issue by RubendeBruin** [wavespectra/wavespectra#33]
The function "spread" in helpers does not produce the correct results.

The spreading is supposed to be symmetric about the mean direction but is cut-off for directions < 0:

![image](https://user-images.githubusercontent.com/34062862/111654357-f9620a80-8808-11eb-98a0-de4918553682.png)

reproduce:
```
from wavespectra.construct.helpers import spread
import numpy as np

dirs = np.arange(0,359)

dp = 30
dspr = 2

s = spread(dp,dspr,dirs)

import matplotlib.pyplot as plt

plt.plot(dirs, s[0])
plt.show()
```

**Comment by RubendeBruin** [comment]
I guess the fix is here:

https://github.com/metocean/wavespectra/blob/master/wavespectra/construct/helpers.py

**Comment by rafa-guedes** [comment]
Thanks for pointing that out @RubendeBruin - This function is part of some unfinished reconstruction work that may get fully rewritten soon

**Comment by RubendeBruin** [comment]
Ok, which parts are going to be re-written? I will stay away from those parts then. I also noticed some inconsistencies in directions when plotting using the contours

**Comment by rafa-guedes** [comment]
I'm closing this as the spectra reconstruction code has been rewritten and is going to be replaced in an upcoming major release.
