### ISSUE TITLE
feature request: interpolation on direction and frequency

### ISSUE THREAD

**Issue by RubendeBruin** [wavespectra/wavespectra#42]
Interpolation/regridding of direction or frequency is currently not implemented.

After merging #40 it is valid to interpolate on the frequency axis.
For interpolation on the direction axis it is needed to consider that 0 = 360. Possibly period=360 will solve that

**Comment by rafa-guedes** [comment]
This will be a great addition and contributions would be welcome! We may want to do a vector interpolation of direction components though rather than interpolating on the directions themselves.

**Comment by RubendeBruin** [comment]
I don't think I fully grasp the concept of vector interpolation in the direction grid. How would that work?

**Comment by rafa-guedes** [comment]
I mean converting directions to vectors and interpolating the vectors. This was in our roadmap to do, there are only a few priorities to be done first..

**Comment by RubendeBruin** [comment]
ok, do I understand correctly that basically that would mean extracting the datapoints to freq*cos(heading), freq*sin(heading). So  that only makes sense when interpolating both frequency and direction at the same time, right?

**Comment by rafa-guedes** [comment]
Implemented in [v3.10.0](https://github.com/wavespectra/wavespectra/tree/v3.10.0)
