### ISSUE TITLE
Log10 plotting option misbehaves

### ISSUE THREAD

**Issue by RubendeBruin** [wavespectra/wavespectra#44]
The "log10" parameter in producing a polar-plot of a spectrum does not do what it should do:

![image](https://user-images.githubusercontent.com/34062862/119074711-13df7c80-ba22-11eb-92f6-756bab27cc0f.png)

![image](https://user-images.githubusercontent.com/34062862/119074724-1cd04e00-ba22-11eb-83f4-d46e8f5960ee.png)

![image](https://user-images.githubusercontent.com/34062862/119074739-23f75c00-ba22-11eb-8234-ac721e447ec9.png)

![image](https://user-images.githubusercontent.com/34062862/119074751-2954a680-ba22-11eb-8e54-076611d3f77e.png)

Reproduce:
```
import numpy as np
import matplotlib.pyplot as plt
import wavespectra
import xarray as xr

dir_bin_width = 10
dirs = np.arange(0,360,dir_bin_width)

start_freq = 0.03125
freq_resolution = 0.0078125
n_frequencies = 37
freqs = [(start_freq + i * freq_resolution) for i in range(0, n_frequencies)]
freqs = np.array(freqs)

# invent a spectrum
s_head = 1 + np.sin(np.deg2rad(dirs))
s_freq = 1 - np.cos(freqs * 6.24 / np.max(freqs))
spec = np.outer(s_head, 0.1*s_freq)

da = xr.DataArray(spec, dims = ('dir','freq'), coords={'dir':dirs, 'freq':freqs}, name = 'efth'
)

plt.figure()
da.spec.plot(as_log10=False)
plt.title('Log10 = False')

plt.figure()
da.spec.plot()
plt.title('Log10 not supplied')

plt.figure()
da.spec.plot(as_log10=True)
plt.title('Log10 = True')

plt.figure()
da.spec.plot()
plt.title('Log10 not supplied')

plt.show()
```

**Comment by rafa-guedes** [comment]
The plotting api has been refactored in #48. I'm going to check a few things but I'm planning to merge it soon. If you don't mind having a quick look at the new code and trying it out that would be nice (if you build the docs there are a few examples on how to use it). Some arguments have been deprecated, among which the `as_log10` one you found the issues with (the same result can be achieved by converting the spectra before calling the plot method).
