### ISSUE TITLE
not all read functions accept Path objects.

### ISSUE THREAD

**Issue by RubendeBruin** [wavespectra/wavespectra#47]
For example read_triaxys can not be called using a Path object as file argument. (pathlib.Path). Converting this to a string works as work-around

**Comment by rafa-guedes** [comment]
Yep these functions never tested with Path objects indeed but it will be an easy fix. The triaxys one in particular checks if input is string or list and ignores any other type. Did you notice this behaviour with other readers besides read_triaxys?

**Comment by RubendeBruin** [comment]
I did not check it for other readers yet.

**Comment by rafa-guedes** [comment]
Fixed with 960460feeec58346f570f86cd39416f33c6ca44a
