### ISSUE TITLE
Read Spotter CSVs

### ISSUE THREAD

**Issue by ryancoe** [wavespectra/wavespectra#66]
Thanks for this very useful project!

The Sofar Spotter buoy dashboard gives `CSV` files when the buoys are deployed (not `JSON`). Is there a reason `wavespectra` only has a a `JSON` reader for Spotters?

It is not a fully generalized function, but maybe this can be used as a starting point: https://github.com/SNL-WaterPower/fbWecCntrl/blob/master/mbari_wec/mbari_wec_2021_example.py

**Comment by rafa-guedes** [comment]
Hi @ryancoe, 

thanks for sending this. @tomdurrant wrote the Spotter reader a while back, I think he got the sample spectra in json only at the time right Tom? If you have an example csv spectra file you are able to share we can have a look at that. Or if you are interested in contributing by writing the spotter csv plugging that would be great too - I can help you out with the basic wavespectra requirements.

Cheers,
Rafael

**Comment by ryancoe** [comment]
@rafa-guedes - Sure thing!

This site has a sample Sofar `csv` file: https://dx.doi.org/10.15473/1825670 (`"Sofar Spotter Buoy Data.csv"`)

I may at some point be able help out with writing a reader for this.  Alternatively, please mention me in the PR and maybe I can lend a hand.

If I understand correctly, I would need to make an `xarray.DataSet` with the following variables:

- 2D spectrum
- Latitude
- Longitude

https://github.com/wavespectra/wavespectra/blob/e3d22d5d38ffe6d01e56a42bc25d30d53a4ecb9c/wavespectra/input/spotter.py#L110-L122

And model the attributes, etc. based on this file: https://github.com/wavespectra/wavespectra/blob/e3d22d5d38ffe6d01e56a42bc25d30d53a4ecb9c/tests/sample_files/wavespectra.nc

Let me know if there's another place I should look that might make this more clear.

**Comment by rafa-guedes** [comment]
Sounds good!

The basic requirements are that the function returns a Dataset with spectral coordinates named as `freq` and `dir` (if 2d) and energy density named as `efth`, with units respectively in `Hz`, `deg` and `m2s/deg`. Other coordinates such as `lat`, `lon`, `site`, wavespectra methods operate along any extra dimension in the dataset. If wind speed, wind direction and water depth are available in the input data it is also good returning these as variables in the dataset named as `wspd`, `wdir`, `dpt` as they are required when doing watershed partitioning.

**Comment by ryancoe** [comment]
@rafa-guedes - I'm working with @cmichelenstrofer on [WecOptTool](https://github.com/SNL-WaterPower/WecOptTool), and we're very glad to be benefitting from your work. This reminded me and gave me the kick in the seat to return to this issue that came up from another project. Anyhow, I think I know how to go about this, but I'm noticing now that [`spotter.py`](https://github.com/wavespectra/wavespectra/blob/master/wavespectra/input/spotter.py) has a object/class based structure while most of the other `input` modules are just function based. Anything I should know here? I don't see a big advantage to having a `Spotter` class based on how I'd use this, but maybe I'm missing something? Unless you prefer otherwise, I'd probably revise [`spotter.py`](https://github.com/wavespectra/wavespectra/blob/master/wavespectra/input/spotter.py) to be something like:

```python
def read_spotter(filename, file_format="json"):
    if file_format is None: # find format based on filename
        pass
    
    if file_format == "json":# import using existing code (probably reorganized to remove class?)
        pass
    elif file_format == "csv":# import using new code
        pass
    else:# raise error
        pass
```

**Comment by rafa-guedes** [comment]
@ryancoe there isn't any strict requirement in terms of having the class definition. Some readers that require lots of processing in order to read (such as the [swan ascii](https://github.com/wavespectra/wavespectra/blob/master/wavespectra/input/swan.py#L22) one) have those classes defined but it could be done in different ways. The only real requirement as defined in the documentation is that the function returns an xarray Dataset in wavespectra conventions so that the SpecArray / SpecDataset assessors can be properly defined.

@tomdurrant has implemented this initial work on the Spotter Json reader, it looks like the class structure was borrowed from the Triaxys reader (I think it only supports reading 1D spectra currently right Tom?). But feel free to revise it when writing the Spotter CSV plugin.
