### ISSUE TITLE
python crashes when importing wavespectra library

### ISSUE THREAD

**Issue by dirkpir** [wavespectra/wavespectra#67]
Hi, thanks for providing such useful tools to the community. Unfortunately, python crashes when I try to import the wavespectra library.
I've installed wavespectra through conda, and am using python (v3.9.7) within the Spyder environment (v5.1.5). Anyone else experiencing such issues or any ideas on how to fix this?
Many thanks,
Dirk

**Comment by dirkpir** [comment]
It seems to work with python v3.8.13

**Comment by rafa-guedes** [comment]
Hi @dirkpir good it worked with python 3.8. Wavespectra has not been tested much with python 3.9 I'm afraid so there may be something that needs to be fixed in the library.

**Comment by rafa-guedes** [comment]
@dirkpir are you still having trouble with this? I have tested it on python 3.8 through 3.10 and it works ok for me.
