### ISSUE TITLE
`wavespectra` depends on, but does not use, `hypothesis`

### ISSUE THREAD

**Issue by Zac-HD** [wavespectra/wavespectra#68]
- Since it's unused, I'd delete the dependency - and check for any other cases of unused dependencies
- In any case, test-time dependencies should not be listed in `install_requires`

**Comment by rafa-guedes** [comment]
this was to fix some other dependency that was breaking due to this library missing I cannot remember now which one

**Comment by Zac-HD** [comment]
Try taking it out?  If it works, done; if it doesn't, revert and open an upstream issue.
