### ISSUE TITLE
ImportError: cannot import name 'read_swan' from 'wavespectra'

### ISSUE THREAD

**Issue by guin0x** [wavespectra/wavespectra#69]
Hi everyone,

I'm trying to plot a 2d spectra from NOAA's buoy data.
I struggled a lot trying to install wavespectra on my PC. In the end, the problem was that I didnt have a fortran compiler installed.

Now I managed to install wavespectra and if I try to ```import wavespectra``` everything works fine...

Now, if I try to do for example ```from wavespectra import read_swan``` (or ```read_ww3```), it doesn't work:

```
      1 import matplotlib.pyplot as plt
      2 import numpy
----> 3 from wavespectra import read_swan

ImportError: cannot import name 'read_swan' from 'wavespectra' 
```

I'm not sure what I'm doing wrong... the reason why I'm looking for a library to do this is because I'm not an oceanographer and I don't know how to plot it myself...

Thanks in advance!

**Comment by rafa-guedes** [comment]
Hi @guin0x 

the installation instructions in the docs don't mention explicitly the requirements for gfortran compiler (and also the need for numpy prior to installing wavespectra), we will improve the docs so it becomes obvious.

On the import error, this traceback does not show much unfortunately. Could you please try importing it from the full path to see if the traceback is more complete? something like:

```
from wavespectra.input.swan import read_swan
```

Also, can you attach some text file with the dump of `pip freeze` so I can try and reproduce the error with your library versions? Maybe try something like:

```
pip freeze > versions.txt
```

then attach that txt file

**Comment by guin0x** [comment]
Hi @rafa-guedes 

Thanks a lot for your help! It worked now.
With ```from wavespectra.input.swan import read_swan``` the error was clearer: 
```
--> 140     raise ImportError("Numba needs NumPy 1.22 or less")
    142 try:
    143     import scipy

ImportError: Numba needs NumPy 1.22 or less
```

I downgraded my numpy to 1.21 and now it works to ```read_swan```.

Is there a thread or place that I can ask questions regarding the funcionalities of the module? (I feel that posting here wouldn't be correct since this is only for issues); but I might have more questions such as ''how should I do this or that''.

Thanks once more!
