### ISSUE TITLE
Automated doc

### ISSUE THREAD

**Issue by rafa-guedes** [wavespectra/wavespectra#7]
sphynx stuff have not been updated since generated a few years back. The main issue with automated building was due to the fortran compilation. @tomdurrant if you could have a look into this when you have some time please it would be great..

**Comment by tomdurrant** [comment]
Yep - I suggest we look into the new github cicd functionality for auto building of docs, and then host on gh-pages instead of readthedocs...

**Comment by rafa-guedes** [comment]
Fixed by building docs from pure-python branch
