### ISSUE TITLE
Spectral reconstruction

### ISSUE THREAD

**Issue by cmichelenstrofer** [wavespectra/wavespectra#76]
The [documentation](https://wavespectra.readthedocs.io/en/latest/api.html#spectral-reconstruction) states

> Spectral reconstruction functionality is under development. There are functions available to fit parametric spectrum shapes from wave partitions but the construct api is not properly established.

We are very interested in seeing this capability in the code. Is this part of the upcoming release? If there is still work to be done we are happy to help. Right now we have coded our own functions to create these parametric directional spectra and put them in `wavespectra`'s format. Ideally we can remove those from our package once `wavespectra` can do it directly. 

In case it is helpful, [this is the relevant file](https://github.com/SNL-WaterPower/WecOptTool/blob/main/wecopttool/waves.py) (starting on line 248). We also have some [tests](https://github.com/SNL-WaterPower/WecOptTool/blob/main/tests/test_waves.py) (e.g. that the integral of the spread function over all directions is 1).

**Comment by rafa-guedes** [comment]
Yes this one of the new features planned for the upcoming major release. Thanks for pointing at your work - there are definitely overlaps in what you did and what we have been working on. Once we merge our work we will welcome contribution on this!

**Comment by RubendeBruin** [comment]
Are you aware of this package : https://docs.4insight.io/waveresponse/python/latest/user_guide/standardized_spectra.html ?

**Comment by rafa-guedes** [comment]
I was not aware. The reconstruction code is done now and will be available in the next major release v4.0 which we are currently working on (https://github.com/wavespectra/wavespectra/pull/106)

**Comment by rafa-guedes** [comment]
Spectra construction has been implemented in v4.0.0. (https://wavespectra.readthedocs.io/en/latest/construction.html). Feedback is welcome!
