### ISSUE TITLE
Plotting the wavespectra figures on the map

### ISSUE THREAD

**Issue by Liu-Jincan** [wavespectra/wavespectra#78]
Hello, everyone! Very thanks this tool for plotting the wavespectra, really useful.
I've succeeded in plotting the figures [in this website](https://wavespectra.readthedocs.io/en/latest/plotting.html) through `wavespectra`.
And I wonder if it's possible to plot the wavespectra figures **on the map**, just like the follow picture,
![image](https://user-images.githubusercontent.com/73934823/202907980-65470ad7-bb35-4573-86ed-30ad025af774.png)
Looking forward to receiving any suggestion. Thanks!

**Comment by rafa-guedes** [comment]
We don't have any plotting function that allows doing that easily but you may be able to do something by mapping map coordinates into figure positions and using that to reposition the axes of the spectra plots.
