### ISSUE TITLE
Read ndbc directional .nc files? Or convert to wavespectra format?

### ISSUE THREAD

**Issue by csherwood-usgs** [wavespectra/wavespectra#79]
This is a great tool! But I don't see a way to read the directional .nc files from the thredds server. When I read them in xarray, I get different variable names. How do I convert the dataset returned in xarray to a wavespectra spec?

`url = 'https://dods.ndbc.noaa.gov/thredds/dodsC/data/swden/42039/42039w2018.nc'`  
`ds = xr.open_dataset(url)`  
`ds`
![image](https://user-images.githubusercontent.com/1618995/207964178-76f8e5dd-b3ad-4297-b6c8-cc307a009fb4.png)

**Comment by rafa-guedes** [comment]
Hi @csherwood-usgs 

The way we deal with dataset conversion is by defining readers within the wavespectra.input module. Description on how to define the input functions are available [here](https://wavespectra.readthedocs.io/en/latest/io-input.html).

There is also some helper reader [read_dataset](https://github.com/wavespectra/wavespectra/blob/master/wavespectra/input/dataset.py) which takes a dataset and guesses how the dataset needs to be modified - but it only supports ww3, wwm and nc_swan formats currently.

Are these datasets from the thredds server consistent? Can we expect the same naming / units when reading data from that (at least for freq/dir coords and for the spectra itself)? If so we could define a new reader function which would take the url as an argument, and perhaps also support it in the read_dataset.

If you need a quick solution you can just rename the `frequency` / `direction` coords into `freq` / `dir`, the energy density array int `efth`, and make sure units are defined as expected in wavespectra (`Hz` for freq, `deg` for dir, `Hz or `Hz/deg` for efth).

**Comment by csherwood-usgs** [comment]
Hi @rafa-guedes 
I understand and appreciate the `read_dataset` readers, and use them to read WW3 and SWAN model output. I am comparing model output with observations. The dataset I'd like to read is the archive of all of the NODC directional wave spectra from buoys. Info is here: https://dods.ndbc.noaa.gov/
and the folders for each buoy is here: https://dods.ndbc.noaa.gov/thredds/catalog/data/swden/catalog.html  
As you can see, this is a pretty big collection of directional wave observations, and probably easier to access than the ASCII files, which cover more limited time intervals. As far as I know, these files are consistent, and I think it would be a big help to the community if you added a reader for this dataset. In the meantime, I will write a function to read this data with xarray and then rename it.

**Comment by rafa-guedes** [comment]
Sounds good @csherwood-usgs this will be useful indeed. We have some reader for the NDBC ascii format but there is a bug in the code, it is not constructing directions correctly at the moment. I was not aware of this netcdf data base. I'll try and implement this soon.

**Comment by rafa-guedes** [comment]
@csherwood-usgs I have implemented some draft reader in branch https://github.com/wavespectra/wavespectra/pull/80. Are you able to review the code please? If you install that branch locally then you should be able to use it by doing something like:

```
from wavespectra import read_ndbc

url = "https://dods.ndbc.noaa.gov/thredds/dodsC/data/swden/42039/42039w2018.nc"
dset = read_ndbc(url)
```

I had issues reading from thredds with the latest version of python-netcdf, I needed to install `netCDF4<1.6.0` in order for this to work.

I ended up moving the existing NDBC ASCII reader which used to be called `read_ndbc` into a different function called `read_ndbc_ascii` given the netcdf version is probably more useful. The new reader does not construct the directional spectra yet, this still needs to be implemented.

**Comment by rafa-guedes** [comment]
I ended also implementing the 2D spectra construction. That definitely needs some review though

**Comment by csherwood-usgs** [comment]
@rafa-guedes  - Thanks so much for implementing this. I have done some initial tests, and it seems to work correctly. I will keep working with it and let you know if any issues arise. Thanks again! - Chris

**Comment by csherwood-usgs** [comment]
Actually, there is a problem...I get all NaNs for the some of the directional data. Is that the netcdf4 issue? I will experiment some more and let you know.

**Comment by rafa-guedes** [comment]
Do you get the nans with that file you mentioned (https://dods.ndbc.noaa.gov/thredds/dodsC/data/swden/42039/42039w2018.nc) or some different file? Let me know how to reproduce it please and I'll have a look as well.

**Comment by csherwood-usgs** [comment]
Yes, I get NaNs trying to read 42039. Also 42003.
This reproduces my problem:
```
url = 'https://dods.ndbc.noaa.gov/thredds/dodsC/data/swden/42003/42003w2018.nc'
ds = xr.open_dataset(url)
print( np.sum(np.isfinite(ds['spectral_wave_density'].values)) )
print( np.sum(np.isfinite(ds['mean_wave_dir'].values)) )
print( np.sum(np.isfinite(ds['principal_wave_dir'].values)) )
print( np.sum(np.isfinite(ds['wave_spectrum_r1'].values)) )
print( np.sum(np.isfinite(ds['wave_spectrum_r2'].values)) )
```
Produces: 
```
345027
0
0
0
0
```
I downloaded the `.nc` file locally and examined it with `ncdump` and verifed there is valid data in the directional arrays.

Here are the results of
`xr.show_versions()`

```
INSTALLED VERSIONS
------------------
commit: None
python: 3.9.15 | packaged by conda-forge | (main, Nov 22 2022, 08:45:29) 
[GCC 10.4.0]
python-bits: 64
OS: Linux
OS-release: 3.10.0-693.2.2.el7.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: ('en_US', 'UTF-8')
libhdf5: 1.12.1
libnetcdf: 4.8.1

xarray: 2022.12.0
pandas: 1.5.2
numpy: 1.23.5
scipy: 1.9.3
netCDF4: 1.5.8
pydap: None
h5netcdf: 1.1.0
h5py: 3.7.0
Nio: None
zarr: 2.13.3
cftime: 1.6.2
nc_time_axis: 1.4.1
PseudoNetCDF: None
rasterio: 1.3.2
cfgrib: None
iris: None
bottleneck: None
dask: 2022.12.0
distributed: 2022.12.0
matplotlib: 3.6.2
cartopy: 0.21.0
seaborn: 0.12.1
numbagg: None
fsspec: 2022.11.0
cupy: None
pint: None
sparse: None
flox: None
numpy_groupies: None
setuptools: 65.5.1
pip: 22.3.1
conda: None
pytest: 7.2.0
mypy: None
IPython: 8.7.0
sphinx: 4.5.0
```

**Comment by rafa-guedes** [comment]
The directional variables seem to be all missing in this file `42039w2018.nc`, please see first few lines of my ncdump below. If this is the case one way forward could be returning 2D spectra when all variables are defined and 1D otherwise.

```
// global attributes:
                :institution = "NOAA National Data Buoy Center and Participators in Data Assembly Center" ;
                :url = "http://dods.ndbc.noaa.gov" ;
                :quality = "Automated QC checks with manual editing and comprehensive monthly QC" ;
                :conventions = "COARDS" ;
                :station = "42003" ;
                :comment = "East GULF - 208 NM West of Naples, FL" ;
                :location = "25.925 N 85.615 W " ;
data:

 principal_wave_dir =
  _,
  _,
  _,
  _,
  _,
  _,
  _,
  _,
  _,
  _,
  _,
  _,
  _,
  _,
  _,
  _,
  _,
  _,
  _,
  _,
  _,
  _,
  _,
  _,
  _,
  _,
  _,
  _,
  _,
  _,

```

**Comment by csherwood-usgs** [comment]
Ugh. You are right...I was sloppy in checking those files. I agree with the suggestion of checking them and treating them as 1d when the directional data are missing. I will continue to test the code.

**Comment by csherwood-usgs** [comment]
Some of the long-term datafiles have an uneven distribution of directional files: 
https://dods.ndbc.noaa.gov/thredds/dodsC/data/swden/42098/42098w9999.nc
2015-06-09T11:00:00.000000000  to  2023-01-03T22:00:00.000000000
Number of non-NaN values in each type of file:
density    3919360
mean dir 3648000
princ dir  3648000
r1            3647904
r2            3647998
However, read_ndbc seems to work on this file and produce a time series of hs.

**Comment by rafa-guedes** [comment]
I have implemented what I suggested above in the [latest commit of nc_ndbc branch](https://github.com/wavespectra/wavespectra/commit/887bd201feeb1f33f906f9c3b21405c85da9d169): it now has an `always_2d` argument which defaults to `False`. When it is False, the function returns 2D if all directional variables have no missing values, and 1D if it detects one single NaN in any of those. If `always_2d` is True however, 2D spectra is always returned. See below an Hs example from the same file plotted before, calculated from the 1D (blue) and 2D (orange) spectra. Note there is missing data in the Hs from the 2D spectra for the timestamps when nan exists in the directional variables.

Let me know if you are happy with this approach or if you have any suggestions please.

```
import matplotlib.pyplot as plt
from wavespectra import read_ndbc

hs1 = read_ndbc("42098w9999.nc").spec.hs()
hs2 = read_ndbc("42098w9999.nc", always_2d=True).spec.hs()
hs1.plot(linewidth=4, label="1D")
hs2.plot(label="2D")
plt.legend()
plt.show()
```

![image](https://user-images.githubusercontent.com/7799184/210751414-65fc98e4-da7e-41d6-b8aa-4400e5cff195.png)

**Comment by rafa-guedes** [comment]
Another option would be always letting the user decide if they want 1D or 2D by having a bool arg `directional` perhaps defaulting to `True`. I think I might actually prefer that as it makes it more transparent.

**Comment by rafa-guedes** [comment]
Implemented in https://github.com/wavespectra/wavespectra/tree/v3.13.0

**Comment by csherwood-usgs** [comment]
@rafa-guedes Thanks for implementing this. I was slow to respond because of HPC issues, that are now resolved. One thing I wanted to test: Only a small fraction of the NDBC buoys measure directional spectra. https://www.ndbc.noaa.gov/dwa.shtml The rest are 1D. It looks to me like they all are in the same format, with missing values in the directional fields when they are 1D spectra. So code that, by default, returns directional spectra when it is available and 1D spectra otherwise seems ideal. I will be doing alot of work with this code, so thank you. We are also working on metrics for comparing models with measurements, and I will share those with you in case you want to implement them. Thanks for working on this!

**Comment by rafa-guedes** [comment]
@csherwood-usgs released a new version yesterday and ended up merging the code with the `directional` argument so at the moment, the user has to specify if they want to get 2D spectra or not.

The way I had implemented it previously, it would return an entire 2D wavespectra dataset if there was no missing data in **the whole** input dataset, otherwise it would return an entire 1D one. We cannot return 1D and 2D in the same wavespectra dataset because the way the library distinguishes between the two is simply by the presence of the `dir` dimension with more than one value in the `efth` DataArray.

In the end, it felt it would be better to be explicit regarding what you want to read rather than letting the code decide how the output would look like. If we need directions, then we specify `directional=True` and we should be aware there will be missing values when directional variables are missing in the NDBC data. If we don't care about directions then we choose `directional=False` which will return the full set of non-directional spectra available, and will be faster to read.

Let me know please if this is a good approach.
