### ISSUE TITLE
Improve compatibility with fsspec

### ISSUE THREAD

**Issue by mpiannucci** [wavespectra/wavespectra#91]
Currently, all the readers (except the zarr one) expect that the input is a filename or list of filenames. This however does not work in a distributed cloud environment where one would typically use `fsspec` to read files straight from a cloud bucket. 

If the readers accept file like objects instead of filenames, the user gains control of the file object and `fsspec` can be used to access files from distributed environments.

**Comment by mpiannucci** [comment]
Sure I will take a stab as a part of #91 ! Thanks for being receptive to this!

**Comment by rafa-guedes** [comment]
Done in https://github.com/wavespectra/wavespectra/pull/92. Now all netcdf- and zarr-based reader functions, plus some ascii-based readers such as read_funwave and read_json accept file-objects as an input and could be used with remote files by using fsspec.

**Comment by mpiannucci** [comment]
Thanks for all your guidance!!

**Comment by rafa-guedes** [comment]
@mpiannucci Code released in [v3.15.1](https://github.com/wavespectra/wavespectra/releases/tag/v3.15.1) (change log [here](https://github.com/wavespectra/wavespectra/blob/master/HISTORY.rst#3151-2023-08-29)). I have added you to the [contributors list](https://github.com/wavespectra/wavespectra/blob/master/AUTHORS.rst) as well
