### ISSUE TITLE
Unable to install wavespectra due to deprecated numpy.distutils

### ISSUE THREAD

**Issue by VincentWervingsdagen** [wavespectra/wavespectra#93]
Hi,

I am trying to install wavespectra with pip in Pycharm, however I get this error:
![image](https://github.com/wavespectra/wavespectra/assets/80783563/dfb6a4f3-80ae-40ab-8276-646110c2d3c7)

Hopefully you can resolve it for the future, I'm going to search around for a solution.

**Comment by VincentWervingsdagen** [comment]
pip install wavespectra
Collecting wavespectra
  Using cached wavespectra-3.15.1.tar.gz (68 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting click (from wavespectra)
  Obtaining dependency information for click from https://files.pythonhosted.org/packages/00/2e/d53fa4befbf2cfa713304affc7ca780ce4fc1fd8710527771b58311a3229/click-8.1.7-py3-none-any.whl.metadata
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting cmocean (from wavespectra)
  Using cached cmocean-3.0.3-py3-none-any.whl (222 kB)
Collecting dask (from wavespectra)
  Obtaining dependency information for dask from https://files.pythonhosted.org/packages/f5/ec/3613b5221a015f54ff50a948029bbd7564e846a45178070feced8b9d105c/dask-2023.9.2-py3-none-any.whl.metadata
  Using cached dask-2023.9.2-py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: matplotlib in c:\users\veng16\pycharmprojects\simple data analysis\venv\lib\site-packages (from wavespectra) (3.7.2)
Collecting numba (from wavespectra)
  Obtaining dependency information for numba from https://files.pythonhosted.org/packages/2c/31/121c11175e49482ef5f8472966f15a02054082c33de6e6a5ca5e59aef3ae/numba-0.58.0-cp39-cp39-win_amd64.whl.metadata
  Using cached numba-0.58.0-cp39-cp39-win_amd64.whl.metadata (2.8 kB)
Requirement already satisfied: numpy in c:\users\veng16\pycharmprojects\simple data analysis\venv\lib\site-packages (from wavespectra) (1.25.2)
Requirement already satisfied: pandas in c:\users\veng16\pycharmprojects\simple data analysis\venv\lib\site-packages (from wavespectra) (2.1.0)
Requirement already satisfied: python-dateutil in c:\users\veng16\pycharmprojects\simple data analysis\venv\lib\site-packages (from wavespectra) (2.8.2)
Collecting pyyaml (from wavespectra)
  Obtaining dependency information for pyyaml from https://files.pythonhosted.org/packages/84/4d/82704d1ab9290b03da94e6425f5e87396b999fd7eb8e08f3a92c158402bf/PyYAML-6.0.1-cp39-cp39-win_amd64.whl.metadata
  Using cached PyYAML-6.0.1-cp39-cp39-win_amd64.whl.metadata (2.1 kB)
Collecting sortedcontainers (from wavespectra)
  Using cached sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Requirement already satisfied: scipy in c:\users\veng16\pycharmprojects\simple data analysis\venv\lib\site-packages (from wavespectra) (1.11.2)
Collecting toolz (from wavespectra)
  Using cached toolz-0.12.0-py3-none-any.whl (55 kB)
Collecting typing-extensions (from wavespectra)
  Obtaining dependency information for typing-extensions from https://files.pythonhosted.org/packages/24/21/7d397a4b7934ff4028987914ac1044d3b7d52712f30e2ac7a2ae5bc86dd0/typing_extensions-4.8.0-py3-none-any.whl.metadata
  Using cached typing_extensions-4.8.0-py3-none-any.whl.metadata (3.0 kB)
Collecting xarray (from wavespectra)
  Obtaining dependency information for xarray from https://files.pythonhosted.org/packages/b5/36/1f4d4bc9be1957716ab93b8be8ea64df6b891ff3fc438f4964916fa6d714/xarray-2023.9.0-py3-none-any.whl.metadata
  Using cached xarray-2023.9.0-py3-none-any.whl.metadata (10 kB)
Collecting colorama (from click->wavespectra)
  Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Requirement already satisfied: packaging in c:\users\veng16\pycharmprojects\simple data analysis\venv\lib\site-packages (from cmocean->wavespectra) (23.1)
Collecting cloudpickle>=1.5.0 (from dask->wavespectra)
  Using cached cloudpickle-2.2.1-py3-none-any.whl (25 kB)
Collecting fsspec>=2021.09.0 (from dask->wavespectra)
  Obtaining dependency information for fsspec>=2021.09.0 from https://files.pythonhosted.org/packages/fe/d3/e1aa96437d944fbb9cc95d0316e25583886e9cd9e6adc07baad943524eda/fsspec-2023.9.2-py3-none-any.whl.metadata
  Using cached fsspec-2023.9.2-py3-none-any.whl.metadata (6.7 kB)
Collecting partd>=1.2.0 (from dask->wavespectra)
  Obtaining dependency information for partd>=1.2.0 from https://files.pythonhosted.org/packages/11/8a/b7a58e208b144a7315208a0dd627e23f5f50b47fa89c2924bb2e9238ecfb/partd-1.4.1-py3-none-any.whl.metadata
  Using cached partd-1.4.1-py3-none-any.whl.metadata (4.6 kB)
Collecting importlib-metadata>=4.13.0 (from dask->wavespectra)
  Obtaining dependency information for importlib-metadata>=4.13.0 from https://files.pythonhosted.org/packages/cc/37/db7ba97e676af155f5fcb1a35466f446eadc9104e25b83366e8088c9c926/importlib_metadata-6.8.0-py3-none-any.whl.metadata
  Using cached importlib_metadata-6.8.0-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\veng16\pycharmprojects\simple data analysis\venv\lib\site-packages (from matplotlib->wavespectra) (1.1.0)
Requirement already satisfied: cycler>=0.10 in c:\users\veng16\pycharmprojects\simple data analysis\venv\lib\site-packages (from matplotlib->wavespectra) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\veng16\pycharmprojects\simple data analysis\venv\lib\site-packages (from matplotlib->wavespectra) (4.42.1)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\veng16\pycharmprojects\simple data analysis\venv\lib\site-packages (from matplotlib->wavespectra) (1.4.5)
Requirement already satisfied: pillow>=6.2.0 in c:\users\veng16\pycharmprojects\simple data analysis\venv\lib\site-packages (from matplotlib->wavespectra) (10.0.0)
Requirement already satisfied: pyparsing<3.1,>=2.3.1 in c:\users\veng16\pycharmprojects\simple data analysis\venv\lib\site-packages (from matplotlib->wavespectra) (3.0.9)
Requirement already satisfied: importlib-resources>=3.2.0 in c:\users\veng16\pycharmprojects\simple data analysis\venv\lib\site-packages (from matplotlib->wavespectra) (6.0.1)
Requirement already satisfied: six>=1.5 in c:\users\veng16\pycharmprojects\simple data analysis\venv\lib\site-packages (from python-dateutil->wavespectra) (1.16.0)
Collecting llvmlite<0.42,>=0.41.0dev0 (from numba->wavespectra)
  Obtaining dependency information for llvmlite<0.42,>=0.41.0dev0 from https://files.pythonhosted.org/packages/79/26/50423498efeca0bf422a0f6d7d5795324403595c15069d35824e8a75732e/llvmlite-0.41.0-cp39-cp39-win_amd64.whl.metadata
  Using cached llvmlite-0.41.0-cp39-cp39-win_amd64.whl.metadata (5.0 kB)
Requirement already satisfied: pytz>=2020.1 in c:\users\veng16\pycharmprojects\simple data analysis\venv\lib\site-packages (from pandas->wavespectra) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\veng16\pycharmprojects\simple data analysis\venv\lib\site-packages (from pandas->wavespectra) (2023.3)
Requirement already satisfied: zipp>=0.5 in c:\users\veng16\pycharmprojects\simple data analysis\venv\lib\site-packages (from importlib-metadata>=4.13.0->dask->wavespectra) (3.16.2)
Collecting locket (from partd>=1.2.0->dask->wavespectra)
  Using cached locket-1.0.0-py2.py3-none-any.whl (4.4 kB)
Using cached click-8.1.7-py3-none-any.whl (97 kB)
Using cached dask-2023.9.2-py3-none-any.whl (1.2 MB)
Using cached PyYAML-6.0.1-cp39-cp39-win_amd64.whl (152 kB)
Using cached numba-0.58.0-cp39-cp39-win_amd64.whl (2.6 MB)
Using cached typing_extensions-4.8.0-py3-none-any.whl (31 kB)
Using cached xarray-2023.9.0-py3-none-any.whl (1.0 MB)
Using cached fsspec-2023.9.2-py3-none-any.whl (173 kB)
Using cached importlib_metadata-6.8.0-py3-none-any.whl (22 kB)
Using cached llvmlite-0.41.0-cp39-cp39-win_amd64.whl (28.1 MB)
Using cached partd-1.4.1-py3-none-any.whl (18 kB)
Building wheels for collected packages: wavespectra
  Building wheel for wavespectra (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for wavespectra (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [88 lines of output]
      <string>:1: DeprecationWarning:
     
        `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
        of the deprecation of `distutils` itself. It will be removed for
        Python >= 3.12. For older Python versions it will remain present.
        It is recommended to use `setuptools < 60.0` for those Python versions.
        For more details, see:
          https://numpy.org/devdocs/reference/distutils_status_migration.html
     
     
      No `packages` or `py_modules` configuration, performing automatic discovery.
      `flat-layout` detected -- analysing .
      discovered packages -- ['wavespectra', 'wavespectra.construct', 'wavespectra.core', 'wavespectra.input', 'wavespectra.output', 'wavespectra.specpart']
      running bdist_wheel
      running build
      running config_cc
      INFO: unifing config_cc, config, build_clib, build_ext, build commands --compiler options
      running config_fc
      INFO: unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
      running build_src
      INFO: build_src
      INFO: building extension "wavespectra.specpart" sources
      INFO: f2py options: []
      INFO:   adding 'build\src.win-amd64-3.9\build\src.win-amd64-3.9\wavespectra\specpart\fortranobject.c' to sources.
      INFO:   adding 'build\src.win-amd64-3.9\build\src.win-amd64-3.9\wavespectra\specpart' to include_dirs.
      INFO:   adding 'build\src.win-amd64-3.9\wavespectra\specpart\specpart-f2pywrappers2.f90' to sources.
      INFO: build_src: building npy-pkg config files
      running build_py
      creating build\lib.win-amd64-cpython-39
      creating build\lib.win-amd64-cpython-39\wavespectra
      copying wavespectra\cli.py -> build\lib.win-amd64-cpython-39\wavespectra
      copying wavespectra\plot.py -> build\lib.win-amd64-cpython-39\wavespectra
      copying wavespectra\specarray.py -> build\lib.win-amd64-cpython-39\wavespectra
      copying wavespectra\specdataset.py -> build\lib.win-amd64-cpython-39\wavespectra
      copying wavespectra\__init__.py -> build\lib.win-amd64-cpython-39\wavespectra
      creating build\lib.win-amd64-cpython-39\wavespectra\construct
      copying wavespectra\construct\helpers.py -> build\lib.win-amd64-cpython-39\wavespectra\construct
      copying wavespectra\construct\jonswap.py -> build\lib.win-amd64-cpython-39\wavespectra\construct
      copying wavespectra\construct\ochihubble.py -> build\lib.win-amd64-cpython-39\wavespectra\construct
      copying wavespectra\construct\__init__.py -> build\lib.win-amd64-cpython-39\wavespectra\construct
      creating build\lib.win-amd64-cpython-39\wavespectra\core
      copying wavespectra\core\attributes.py -> build\lib.win-amd64-cpython-39\wavespectra\core
      copying wavespectra\core\npstats.py -> build\lib.win-amd64-cpython-39\wavespectra\core
      copying wavespectra\core\select.py -> build\lib.win-amd64-cpython-39\wavespectra\core
      copying wavespectra\core\swan.py -> build\lib.win-amd64-cpython-39\wavespectra\core
      copying wavespectra\core\utils.py -> build\lib.win-amd64-cpython-39\wavespectra\core
      copying wavespectra\core\watershed.py -> build\lib.win-amd64-cpython-39\wavespectra\core
      INFO: CCompilerOpt.cache_flush[863] : write cache to path -> C:\Users\veng16\AppData\Local\Temp\pip-install-gogyv6y1\wavespectra_539a5f32e7034623b70539dbd61bccdd\build\temp.win-amd64-cpython-39\Release\ccompiler_opt_cache_
ext.py
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for wavespectra
Failed to build wavespectra
ERROR: Could not build wheels for wavespectra, which is required to install pyproject.toml-based projects

**Comment by rafa-guedes** [comment]
Hi @VincentWervingsdagen,

Do you know if it is the `DeprecationWarning` of `numpy.distutils` that is causing the install to fail in PyCharm? I had similar issues a little while ago when trying to install wavespectra inside some github action workflow. This is what prompted me to replace the old install with `setup.py` by `pyproject.toml` in https://github.com/wavespectra/wavespectra/pull/87. There is still a [setup.py](https://github.com/wavespectra/wavespectra/blob/master/setup.py) there now but all it is doing is use `numpy.distutils` to handle the install of the fortran extension required by the watershed code. Ideally this fortran extension install should be replaced given numpy.distutils will go away in `python>=3.12` but I haven't been able to solve that yet (any help on this would be appreciated). The supported python versions defined in pyproject are up to python 3.10 though - are you trying to install it in python 3.12?

**Comment by VincentWervingsdagen** [comment]
Oh yes, I'm using python 3.12. I forgot to check the supported versions. I'm currently unable to help as my internship is enough work as it is :).
