### ISSUE TITLE
numpy<=1.25

### ISSUE THREAD

**Issue by ryancoe** [wavespectra/wavespectra#95]
I got the following error with numpy 1.25.2, which was fixed by doing `pip install "numpy<=1.25"` - it seems like you may need to specify `numpy<=1.25`?

https://github.com/wavespectra/wavespectra/blob/149516ce5f57a7f16517471d46c2b26b88c68075/pyproject.toml#L39

<details>
  <summary>Error output</summary>

```
In [1]: import wavespectra.specarray
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[1], line 1
----> 1 import wavespectra.specarray

File ~/mambaforge/envs/wot_dev/lib/python3.11/site-packages/wavespectra/specarray.py:21
     19 from wavespectra.core.attributes import attrs
     20 from wavespectra.core.utils import D2R, R2D, celerity, wavenuma, wavelen, regrid_spec
---> 21 from wavespectra.core import xrstats
     22 from wavespectra.plot import polar_plot, CBAR_TICKS
     24 from typing_extensions import deprecated

File ~/mambaforge/envs/wot_dev/lib/python3.11/site-packages/wavespectra/core/xrstats.py:6
      3 import xarray as xr
      5 from wavespectra.core.attributes import attrs
----> 6 from wavespectra.core import npstats
      9 def peak_wave_direction(dset):
     10     """Peak wave direction Dp.
     11 
     12     Args:
   (...)
     17 
     18     """

File ~/mambaforge/envs/wot_dev/lib/python3.11/site-packages/wavespectra/core/npstats.py:3
      1 """Wave spectra stats on numpy arrays sourced by apply_ufuncs."""
      2 import numpy as np
----> 3 from numba import guvectorize
      5 from wavespectra.core.utils import D2R, R2D
      8 def hs(spectrum, freq, dir, tail=True):

File ~/mambaforge/envs/wot_dev/lib/python3.11/site-packages/numba/__init__.py:55
     50             msg = ("Numba requires SciPy version 1.0 or greater. Got SciPy "
     51                    f"{scipy.__version__}.")
     52             raise ImportError(msg)
---> 55 _ensure_critical_deps()
     56 # END DO NOT MOVE
     57 # ---------------------- WARNING WARNING WARNING ----------------------------
     60 from ._version import get_versions

File ~/mambaforge/envs/wot_dev/lib/python3.11/site-packages/numba/__init__.py:42, in _ensure_critical_deps()
     40     raise ImportError(msg)
     41 elif numpy_version > (1, 25):
---> 42     raise ImportError("Numba needs NumPy 1.25 or less")
     43 try:
     44     import scipy

ImportError: Numba needs NumPy 1.25 or less
```

```matlab
a = 1+1
```

</details>

**Comment by rafa-guedes** [comment]
Did you upgrade numpy in your environment? Numba usually pins numpy so when we install wavespectra the dependencies should sort themselves (they have been so far with me at least). In saying that we may want to remove numpy from the explicit dependencies in pyproject.toml, I'll have a look into that.

**Comment by rafa-guedes** [comment]
I have installed wavespectra on a new environment and all seems to be working ok. These versions have been installed:

```
(test) ➜  wavespectra git:(master) ✗ pip freeze | grep numpy
numpy==1.26.1
(test) ➜  wavespectra git:(master) ✗ pip freeze | grep numba
numba==0.58.1
```

**Comment by ryancoe** [comment]
hmmm... I should've perhaps mentioned that I'm using macos 13.6 with an arm64 processor, so perhaps that's creating some special result. I agree with letting numba and numpy work out their version requirements themselves, which does indeed seem to be the problem.

**Comment by rafa-guedes** [comment]
I have removed numpy from the dependencies in master, it isn't released yet. Do you get the problem when installing wavespectra on a clean environment?

**Comment by ryancoe** [comment]
This may be an `arm64` specific issue, but here's what I get:

```zsh
mamba create -n tmp_ws
mamba activate tmp_ws
mamba install pip
pip install wavespectra
```

```zsh
Collecting wavespectra
  Downloading wavespectra-3.15.1.tar.gz (68 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.6/68.6 kB 413.9 kB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "/Users/rcoe/mambaforge/envs/tmp_ws/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/rcoe/mambaforge/envs/tmp_ws/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/rcoe/mambaforge/envs/tmp_ws/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/79/8lsmfjgd51sfh8wmmtc_xr9c002j5n/T/pip-build-env-3ksblum2/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/79/8lsmfjgd51sfh8wmmtc_xr9c002j5n/T/pip-build-env-3ksblum2/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/79/8lsmfjgd51sfh8wmmtc_xr9c002j5n/T/pip-build-env-3ksblum2/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 1, in <module>
      ModuleNotFoundError: No module named 'numpy.distutils'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by rafa-guedes** [comment]
What python version are you running on? This looks similar to https://github.com/wavespectra/wavespectra/issues/93 which was caused by numpy's distutil removal from python 3.12. We [currently support](https://github.com/wavespectra/wavespectra/blob/master/pyproject.toml#L27-L30) python up to 3.10 only (although that isn't defined in the [requires-python](https://github.com/wavespectra/wavespectra/blob/master/pyproject.toml#L32) variable which says >=3.8).

I'll change the `requires-python` variable for now so the issue is hopefully prevented. The longer term solution though is find an alternative method to [build the watershed module from the fortran code](https://github.com/wavespectra/wavespectra/blob/master/setup.py) which currently uses `numpy.distutil`. I had a quick look on other methods but didn't get that to work yet and I don't have a lot of time at the moment to work on this. If someone would be keen to have a look at alternatives that would be really appreciated!

**Comment by rafa-guedes** [comment]
I have opened a new issue https://github.com/wavespectra/wavespectra/issues/96 for the numpy.distutil problem. Let me know please if you still have the other issue with numba/numpy conflict when installing it on a clean environment (with python<3.12).

**Comment by ryancoe** [comment]
Yes, it looks like when I installed `pip` it went with `python 3.12`, and then didn't force any changes for the `python` version when I call `pip install wavespectra`. When I do `mamba install python==3.10` and then `pip install wavespectra`, it all works fine, so I think changing `requires-python` will resolve the problem.

**Comment by rafa-guedes** [comment]
The latest release 3.15.2 should fix the issues discussed here:

- requires-python defined to avoid installing wavespectra in python 3.12
- numpy removed from the requirements so numba can sort it out what it needs avoiding conflicts.
