### ISSUE TITLE
Unable to install wavespectra ERROR not build wheels for wavespectra

### ISSUE THREAD

**Issue by mjr994** [wavespectra/wavespectra#97]
Unable to install wavespectra, this is the error I get when using: pip install wavespectra.
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for wavespectra
Failed to build wavespectra
ERROR: Could not build wheels for wavespectra, which is required to install pyproject.toml-based projects

I already installed pyproject.toml-based.

**Comment by rafa-guedes** [comment]
Is there more traceback you could paste here please? What python version are you trying to install wavespectra on?

**Comment by mjr994** [comment]
I'm using python 3.8.2. I have a lot of output:

failed with exit status 1 output ->
      /private/var/folders/6c/sr_ktyxn1k39dl6y4n2x5xzm0000gn/T/pip-build-env-vwjkda0z/overlay/lib/python3.9/site-packages/numpy/distutils/checks/cpu_avx512_spr.c:20:2: error:
      #error
       ^
      /private/var/folders/6c/sr_ktyxn1k39dl6y4n2x5xzm0000gn/T/pip-build-env-vwjkda0z/overlay/lib/python3.9/site-packages/numpy/distutils/checks/cpu_avx512_spr.c:22:12: error: expected ';' after expression
          __m512h a = _mm512_loadu_ph((void*)argv[argc-1]);
                 ^
                 ;
      /private/var/folders/6c/sr_ktyxn1k39dl6y4n2x5xzm0000gn/T/pip-build-env-vwjkda0z/overlay/lib/python3.9/site-packages/numpy/distutils/checks/cpu_avx512_spr.c:22:5: error: use of undeclared identifier '__m512h'
          __m512h a = _mm512_loadu_ph((void*)argv[argc-1]);
          ^
      /private/var/folders/6c/sr_ktyxn1k39dl6y4n2x5xzm0000gn/T/pip-build-env-vwjkda0z/overlay/lib/python3.9/site-packages/numpy/distutils/checks/cpu_avx512_spr.c:22:13: error: use of undeclared identifier 'a'
          __m512h a = _mm512_loadu_ph((void*)argv[argc-1]);
                  ^
      /private/var/folders/6c/sr_ktyxn1k39dl6y4n2x5xzm0000gn/T/pip-build-env-vwjkda0z/overlay/lib/python3.9/site-packages/numpy/distutils/checks/cpu_avx512_spr.c:22:17: error: implicit declaration of function '_mm512_loadu_ph' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
          __m512h a = _mm512_loadu_ph((void*)argv[argc-1]);
                      ^
      /private/var/folders/6c/sr_ktyxn1k39dl6y4n2x5xzm0000gn/T/pip-build-env-vwjkda0z/overlay/lib/python3.9/site-packages/numpy/distutils/checks/cpu_avx512_spr.c:23:12: error: expected ';' after expression
          __m512h temp = _mm512_fmadd_ph(a, a, a);
                 ^
                 ;
      /private/var/folders/6c/sr_ktyxn1k39dl6y4n2x5xzm0000gn/T/pip-build-env-vwjkda0z/overlay/lib/python3.9/site-packages/numpy/distutils/checks/cpu_avx512_spr.c:23:5: error: use of undeclared identifier '__m512h'
          __m512h temp = _mm512_fmadd_ph(a, a, a);
          ^
      /private/var/folders/6c/sr_ktyxn1k39dl6y4n2x5xzm0000gn/T/pip-build-env-vwjkda0z/overlay/lib/python3.9/site-packages/numpy/distutils/checks/cpu_avx512_spr.c:23:13: error: use of undeclared identifier 'temp'
          __m512h temp = _mm512_fmadd_ph(a, a, a);
                  ^
      /private/var/folders/6c/sr_ktyxn1k39dl6y4n2x5xzm0000gn/T/pip-build-env-vwjkda0z/overlay/lib/python3.9/site-packages/numpy/distutils/checks/cpu_avx512_spr.c:23:20: error: implicit declaration of function '_mm512_fmadd_ph' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
          __m512h temp = _mm512_fmadd_ph(a, a, a);
                         ^
      /private/var/folders/6c/sr_ktyxn1k39dl6y4n2x5xzm0000gn/T/pip-build-env-vwjkda0z/overlay/lib/python3.9/site-packages/numpy/distutils/checks/cpu_avx512_spr.c:23:36: error: use of undeclared identifier 'a'
          __m512h temp = _mm512_fmadd_ph(a, a, a);
                                         ^
      /private/var/folders/6c/sr_ktyxn1k39dl6y4n2x5xzm0000gn/T/pip-build-env-vwjkda0z/overlay/lib/python3.9/site-packages/numpy/distutils/checks/cpu_avx512_spr.c:23:39: error: use of undeclared identifier 'a'
          __m512h temp = _mm512_fmadd_ph(a, a, a);
                                            ^
      /private/var/folders/6c/sr_ktyxn1k39dl6y4n2x5xzm0000gn/T/pip-build-env-vwjkda0z/overlay/lib/python3.9/site-packages/numpy/distutils/checks/cpu_avx512_spr.c:23:42: error: use of undeclared identifier 'a'
          __m512h temp = _mm512_fmadd_ph(a, a, a);
                                               ^
      /private/var/folders/6c/sr_ktyxn1k39dl6y4n2x5xzm0000gn/T/pip-build-env-vwjkda0z/overlay/lib/python3.9/site-packages/numpy/distutils/checks/cpu_avx512_spr.c:24:5: error: implicit declaration of function '_mm512_storeu_ph' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
          _mm512_storeu_ph((void*)(argv[argc-1]), temp);
          ^
      /private/var/folders/6c/sr_ktyxn1k39dl6y4n2x5xzm0000gn/T/pip-build-env-vwjkda0z/overlay/lib/python3.9/site-packages/numpy/distutils/checks/cpu_avx512_spr.c:24:45: error: use of undeclared identifier 'temp'
          _mm512_storeu_ph((void*)(argv[argc-1]), temp);
14 errors generated.
      
      WARN: CCompilerOpt.feature_test[1575] : testing failed
      INFO: CCompilerOpt.__init__[1815] : skip features (SSE3 SSE2 SSE) since its part of baseline
      INFO: CCompilerOpt.__init__[1819] : initialize targets groups
      INFO: CCompilerOpt.__init__[1821] : parse target group simd_test
      INFO: CCompilerOpt._parse_target_tokens[2032] : skip targets (VXE XOP VSX3 NEON VXE2 VX FMA4 VSX ASIMD VSX4 VSX2) not part of baseline or dispatch-able features
      INFO: CCompilerOpt._parse_policy_not_keepbase[2144] : skip baseline features (SSE2)
      INFO: CCompilerOpt.generate_dispatch_header[2365] : generate CPU dispatch header: (build/src.macosx-10.9-x86_64-3.9/numpy/distutils/include/npy_cpu_dispatch_config.h)
      WARN: CCompilerOpt.generate_dispatch_header[2374] : dispatch header dir build/src.macosx-10.9-x86_64-3.9/numpy/distutils/include does not exist, creating it
      INFO: CCompilerOpt.feature_extra_checks[1639] : Testing extra checks for feature 'AVX512F' (AVX512F_REDUCE)
      extra options: '-msse -msse2 -msse3 -mssse3 -msse4.1 -mpopcnt -msse4.2 -mavx -mf16c -mfma -mavx2 -mavx512f -mno-mmx -mavx512cd -mavx512vl -mavx512bw -mavx512dq -Werror=switch -Werror'
      INFO: get_default_fcompiler: matching types: '['gnu95', 'nag', 'nagfor', 'absoft', 'ibm', 'intel', 'gnu', 'g95', 'pg']'
      INFO: customize Gnu95FCompiler
      WARN: Could not locate executable gfortran
      WARN: Could not locate executable f95
      INFO: customize NAGFCompiler
      INFO: customize NAGFORCompiler
      WARN: Could not locate executable nagfor
      INFO: customize AbsoftFCompiler
      WARN: Could not locate executable f90
      WARN: Could not locate executable f77
      INFO: customize IBMFCompiler
      WARN: Could not locate executable xlf90
      WARN: Could not locate executable xlf
      INFO: customize IntelFCompiler
      WARN: Could not locate executable ifort
      WARN: Could not locate executable ifc
      INFO: customize GnuFCompiler
      WARN: Could not locate executable g77
      INFO: customize G95FCompiler
      WARN: Could not locate executable g95
      INFO: customize PGroupFCompiler
      WARN: Could not locate executable pgfortran
      WARN: don't know how to compile Fortran code on platform 'posix'
      warning: build_ext: f77_compiler=None is not available.
      
      INFO: building 'wavespectra.specpart' extension
      error: extension 'wavespectra.specpart' has Fortran sources but no Fortran compiler found
      INFO:
      ########### EXT COMPILER OPTIMIZATION ###########
      INFO: Platform      :
        Architecture: x64
        Compiler    : clang
      
      CPU baseline  :
        Requested   : 'min'
        Enabled     : SSE SSE2 SSE3
        Flags       : -msse -msse2 -msse3
        Extra checks: none
      
      CPU dispatch  :
        Requested   : 'max -xop -fma4'
        Enabled     : SSSE3 SSE41 POPCNT SSE42 AVX F16C FMA3 AVX2 AVX512F AVX512CD AVX512_KNL AVX512_SKX AVX512_CLX AVX512_CNL AVX512_ICL
        Generated   : none
      INFO: CCompilerOpt.cache_flush[863] : write cache to path -> /private/var/folders/6c/sr_ktyxn1k39dl6y4n2x5xzm0000gn/T/pip-install-hhgsr77k/wavespectra_6f89ce45644649a59a6d75b73a8c2cdb/build/temp.macosx-10.9-x86_64-cpython-39/ccompiler_opt_cache_ext.py
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for wavespectra
Failed to build wavespectra
ERROR: Could not build wheels for wavespectra, which is required to install pyproject.toml-based projects

**Comment by rafa-guedes** [comment]
You need a fortran compiler to install wavespectra because it has some fortran code used for the watershed partitioning that needs to be compiled. You could try installing gfortran, it looks like you are on mac so [this](https://resources.xmaptools.ch/install-gfortran/) might be helpful. Alternatively, you could try and install it from [conda](https://wavespectra.readthedocs.io/en/latest/install.html#install-from-conda) - conda should take care of your whole environment including the compiler.

**Comment by mjr994** [comment]
Thanks, this works! :)
