### ISSUE TITLE
Integrating 2D spectra

### ISSUE THREAD

**Issue by achat97** [wavespectra/wavespectra#99]
Hi, I am trying to plot a 1D spectrum of the output from WW3. Is there any way to integrate the spectra over space in order to get a spectral density spectrum with m^2 s , instead of m2 s degree-1?

**Comment by rafa-guedes** [comment]
Yes, just do something like 

    dset_1d = dset.spec.oned()

**Comment by achat97** [comment]
Ah, okay so it was .oned(). It seems like I am not getting it to work. I assume it is supposed to have an attribute, like the other integration methods, but I only get the coordiates. I get the following output when i run my code, along with this error:

```
UserWarning: rename 'time' to 'time' does not create an index anymore. Try using swap_dims instead or use set_index after rename to create an indexed coordinate.
  dset = dset.rename(MAPPING)
<xarray.DataArray 'efth' (time: 61, site: 1, freq: 36)>
dask.array<mul, shape=(61, 1, 36), dtype=float32, chunksize=(61, 1, 36), chunktype=numpy.ndarray>
Coordinates:
  * time     (time) datetime64[ns] 1968-06-06 ... 1968-06-08T12:00:00
  * site     (site) float64 1.0
  * freq     (freq) float32 0.0485 0.05335 0.05868 0.06455 ... 1.126 1.239 1.363
```

**Comment by rafa-guedes** [comment]
Your output is okay - you may be confused by the fact the method returns a DataArray even though you ran it from a Dataset with an `efth` variable in it. Most methods in wavespectra such as hs(), tp(), oned(), etc operate on and return a DataArray regardless you initially had a DataArray or a Dataset object (this is something I am considering to change in the future though as I agree it could be convenient to preserve the type of the initial object).

Your warning is nothing to be concerned about and will go away in a future major release.

**Comment by achat97** [comment]
Yes, I was a little confused about that because I initially tried to plot it as you do with hs and the other methods, i.e. with plot.line(). But I figured out now that you plot it the same way as the 2D spectra. 

Thank you for your help!
